### PR TITLE
Replace deprecated publish plugin

### LINKED ISSUE #654: Deployment is failing due to deprecation of nexus-publish-plugin
**Description**
The [OSSRH workflow](https://github.com/meilisearch/meilisearch-java/actions/runs/6175913305/job/16782421217) failed during the v0.11.2 deployment.
This is caused by the deprecation of the [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin/) which is used by [gradle-nexus-staging-plugin](https://github.com/Codearte/gradle-nexus-staging-plugin) that we currently use in the `build.gradle` file.
The nexus-publish-plugin is now replaced by [this publish plugin](https://github.com/gradle-nexus/publish-plugin).

**Screenshots or Logs**
```
> Task :closeRepository
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
Attempt 61/61 failed. WrongNumberOfRepositories was thrown with message 'Wrong number of received repositories in state 'open'. Expected 1, received 3'. Giving up. Configure longer timeout if necessary.

> Task :closeRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
1 actionable task: 1 executed
Execution failed for task ':closeRepository'.
> Wrong number of received repositories in state 'open'. Expected 1, received 3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 5m 11s
Error: Process completed with exit code 1.
```

**How to fix it**

You should be able to follow this guide for the [migration](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) and modify the `build.gradle` file with the new plugin

### PR DESCRIPTION
**Pull request by axelrindle**
# Pull Request

## Related issue
Fixes #654 

## What does this PR do?
Replaces the deprecated Gradle Publish Plugin with a new one.

Requires additional testing as I do not possess a Sonatype Account.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by axelrindle** [comment]
Unfortunately I can't really help with this...

But I found some issues that may help:

- gradle-nexus/publish-plugin#211
- gradle-nexus/publish-plugin#217

Could be you need to configure something in Sonatype directly? Or are there other secrets that could be used?

**Comment by KaaNee** [comment]
Have a look at the Background-Tasks of the new plugin, maybe this helps.

https://github.com/gradle-nexus/publish-plugin/#behind-the-scenes
See second point: 

> creates a retrieve{repository.name.capitalize()}StagingProfile task that retrieves the staging profile id from the remote Nexus repository. This is a diagnostic task to enable setting the configuration property stagingProfileId in nexusPublishing { repositories { myRepository { ... } } }. Specifying the configuration property rather than relying on the API call is considered a performance optimization.

Specify the 'stagingProfileId' if your nexus won't return it on request as explained above (or adapt the nexus config)

**Comment by axelrindle** [comment]
I agree with @KaaNee. Only someone with Nexus/Sonatype access can fix this issue.

**Comment by alallema** [comment]
Thank you so much for this PR @axelrindle and for your help @KaaNee 😊 

I took the liberty of modifying your PR, I think I've found a solution, probably not the cleanest, but it works if the two tasks are in the same command.
You can check the [successful deployment here](https://github.com/meilisearch/meilisearch-java/actions/runs/6615672365/job/17968316068?pr=673) 🎉

**Review by curquiza — APPROVED** [review]
thank you all!

bors merge

**Comment by curquiza** [comment]
Issue with bors again... Merging by hand

**Pull request merged**
