### PR TITLE
Add details field to Task class

### LINKED ISSUE #331: Adding `details` field to `Task` class
The Java class `Task` which retrieves the response from `Meilisearch` for a task contains these fields:
```
    protected String status = "";
    protected int uid = 0;
    protected String indexUid = "";
    protected String type = null;
    protected String duration = "";
    protected Date enqueuedAt = null;
    protected Date startedAt = null;
    protected Date finishedAt = null;
    protected TaskError error = null;
```
But the actual response send by `Meilisearch` is like:
```
{
	"uid": 225,
	"indexUid": "WaitForTaskTimoutInMs",
	"status": "succeeded",
	"type": "documentAddition",
	"details": {
		"receivedDocuments": 30,
		"indexedDocuments": 30
	},
	"duration": "PT0.031713875S",
	"enqueuedAt": "2022-01-26T16:54:46.993341418Z",
	"startedAt": "2022-01-26T16:54:46.995596001Z",
	"finishedAt": "2022-01-26T16:54:47.027309876Z"
},
```
It should be more accurate to add a `details` field to the `Task` class to be able to have the entire answer from the `Meilisearch` API.

### PR DESCRIPTION
**Pull request by kuruvasatya**
# Pull Request

## What does this PR do?
Fixes #331 

created new class Details with two fields, and added Details class object as a field in Task class

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Hi @kuruvasatya,
Thanks for this PR! I have not detailed enough the issue but `details` can contains differents fields in the case of `indexCreation` you will have:
```json
    "type": "indexCreation",
        "details": {
            "primaryKey": null
        },
```
In case of `indexDeletion`:
```json
    "type": "indexDeletion",
        "details": {
            "deletedDocuments": 30
        },
```
And others.
I think that's why the tests don't work.
Don't hesitate if you have more questions.

**Comment by kuruvasatya** [comment]
Hi @alallema,
Thanks for reviewing my PR, I have another idea, we can use `Map<String, String> details ` in Task class to add details field, whats your take on this?

Also i have issues with linting, i am not able to find what is the real issue is... If you dont mind Can you please help me with that?

**Comment by bidoubiwa** [comment]
There some types missing: See [example](https://github.com/meilisearch/meilisearch-swift/blob/91825b83431e909cca6a3c0445c15148050846b6/Sources/MeiliSearch/Model/Task.swift#L37)

**Comment by alallema** [comment]
@kuruvasatya, I see you open a new PR #336 did I close this one?

**Pull request closed without merging**
