### PR TITLE
add package version to Jupiter

### PR DESCRIPTION
**Pull request by fharper**
that fixes the dependencies.dependency.version missing error when adding our package to a project

### CODE REVIEW

**Comment by eskombro** [comment]
bors try

**Comment by eskombro** [comment]
Thanks @fharper !

Bors merge

**Review by eskombro — APPROVED** [review]
🎉

**Comment by eskombro** [comment]
Bors merge

**Comment by fharper** [comment]
Yeah! My first PR merged on our integrations 🎉

**Comment by curquiza** [comment]
You're now an official contributor! 🚀

**Pull request merged**
