### PR TITLE
make Class Error accesible

### PR DESCRIPTION
**Pull request by Artumira96**
# Pull Request

## What does this PR do?
Solves issue #292

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @Artumira96 for this PR.
I think your code addition should work but it doesn't pass the tests. Probably because the compiler requires a public class to be in a file with its name.
I let you check the  [CONTRIBUTING](https://github.com/meilisearch/meilisearch-java/blob/main/CONTRIBUTING.md). I can merge your PR if the tests didn't pass.
Also, can you just add or modify an existing test to try one of your new getter, setter?

Thanks for contributing to MeiliSearch ❤️

**Comment by Artumira96** [comment]
Thanks for the feedback! , I got the test running for the getter and setter:
Screen Shot 2021-12-21 at 13 56 55
 
I also changed the 'Error' class to 'UpdateStatusError', on its own file and every test passes now:
Screen Shot 2021-12-21 at 14 06 00

Hope this fixes the issue now, I'll be around for anything else :) Thanks!

**Comment by Artumira96** [comment]
I discovered I was having issues with the formatting, I ran the lint script:
Screen Shot 2021-12-22 at 15 06 19


and also the integration tests and it's working fine for me:
Screen Shot 2021-12-22 at 15 07 53

Thanks in advance for your patience, regards.

**Review by alallema — APPROVED** [review]
LGTM! ✨

**Comment by alallema** [comment]
bors merge

**Pull request merged**
