### PR TITLE
Update generic exception `MeilisearchException` to throw more accurate Exception

### LINKED ISSUE #678: Refining exception throws
**Description**

Currently, the exceptions thrown are all `MeilisearchException`. 
This makes it difficult for the user to specify which exception was thrown. 

**Basic example**

The way to fix this is to throw all exceptions as-is.
Instead, the practice of creating and throwing `MeilsearchException` directly should be eliminated.

AS-IS

```java
public <T> HttpResponse<T> execute(HttpRequest request) throws MeilisearchException {
    try {
        Request okRequest = buildRequest(request);
        Response response = client.newCall(okRequest).execute();

        return buildResponse(response);
    } catch (MalformedURLException e) {
        throw new MeilisearchException(e); // do not throw MeilisearchException directly!
    } catch (SocketTimeoutException e) {
        throw new MeilisearchTimeoutException(e);
    } catch (IOException e) {
        throw new MeilisearchCommunicationException(e);
    }
}
```

TO-BE

```java
public <T> HttpResponse<T> execute(HttpRequest request)
    throws MeilisearchURLException, MeilisearchTimeoutException, MeilisearchCommunicationException {
    try {
        Request okRequest = buildRequest(request);
        Response response = client.newCall(okRequest).execute();

        return buildResponse(response);
    } catch (MalformedURLException e) {
        throw new MeilisearchURLException(e); // for example
    } catch (SocketTimeoutException e) {
        throw new MeilisearchTimeoutException(e);
    } catch (IOException e) {
        throw new MeilisearchCommunicationException(e);
    }
}
```

**Other**
This issue has great synergy when applied with #677.
If all exceptions were `RuntimeException`, we wouldn't need any code to re-throw.

```java
public <T> HttpResponse<T> execute(HttpRequest request) { // we don't have to re-throw!
    try {
        Request okRequest = buildRequest(request);
        Response response = client.newCall(okRequest).execute();

        return buildResponse(response);
    } catch (MalformedURLException e) {
        throw new MeilisearchURLException(e); // for example
    } catch (SocketTimeoutException e) {
        throw new MeilisearchTimeoutException(e);
    } catch (IOException e) {
        throw new MeilisearchCommunicationException(e);
    }
}
```

### PR DESCRIPTION
**Pull request by 239yash**
# Pull Request

## Related issue
Fixes #678 

## What does this PR do?
- PR updates the generic exception(MeilisearchException) throws from function to exact exception throws
- Created a new exception MeilisearchUrlException for handling MalformedUrlException 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
Hello @239yash 

thank you for your PR

Could you add integration tests to ensure the right exception are called in the right situation?

**Comment by 239yash** [comment]
Hi @curquiza 
Yes, I will add the integration tests too. Thanks

**Comment by 239yash** [comment]
@curquiza hi, I am working on this. I will submit the PR by coming weekend. Thanks

**Comment by curquiza** [comment]
Closing this for lack of activity. Feel free to re-open of course if you have time to work on it @239yash ❤️ 
I'm just doing some cleaning

**Pull request closed without merging**
