### PR TITLE
Standardize health method

### PR DESCRIPTION
**Pull request by alallema**
**Description**
Checking that method health() return {'status': 'available'} and added isHealthy() method who return boolean value

**Issue related**
meilisearch/integration-guides#55

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
Is the `isHealth` method tested?

**Comment by alallema** [comment]
> Is the `isHealth` method tested?

Yes, the `isHealthy` method was already tested.

**Review by curquiza — APPROVED** [review]
waiting for @eskombro 

Thanks @alallema! :)

**Comment by alallema** [comment]
bors merge

**Pull request merged**
