### PR TITLE
Add check release script

### LINKED ISSUE #140: Add a check-release script
Currently, there is no check that the version of the package that will be published match the release tag.
We want to implement the check when the publish workflow is triggered (`ossrh-publish.yml`)

⚠️ Should be done by a MeiliSearch team member.

### PR DESCRIPTION
**Pull request by curquiza**
Closes #140 

I tested it this way to "immitate" the GitHub action behavior:

Capture d’écran 2021-03-20 à 19 36 50

### CODE REVIEW

**Review by eskombro — APPROVED** [review]
Amazing, thanks!!!  

🌮

**Comment by eskombro** [comment]
Should we add it to our CI on this PR?

**Comment by curquiza** [comment]
> Should we add it to our CI on this PR?

Not sure to understand. Do you mean the CI containing tests we launch on each PR? Because it's only checkable when pushing a tag

**Comment by nicolasvienot** [comment]
Perfect, thanks! 😊 

I think this should be added to the` ossrh-publish` workflow in order to check the version before the publication in the Central Repository

**Review by nicolasvienot — CHANGES_REQUESTED** [review]
Perfect, thanks! 😊

I think this should be added to the ossrh-publish workflow in order to check the version before the publication in the Central Repository

**Comment by curquiza** [comment]
> I think this should be added to the ossrh-publish workflow in order to check the version before the publication in the Central Repository

Oh yes I forgot the most important!! 😂 Thanks nico!!

**Review by eskombro — APPROVED** [review]

**Review by nicolasvienot — APPROVED** [review]
Perfect 👍

**Comment by eskombro** [comment]
Bors merge

**Pull request merged**
