### PR TITLE
Add delete documents by

### PR DESCRIPTION
**Pull request by widlok**
#42 added implementation and tests.
Regards Chris

### CODE REVIEW

**Review by djKooks — APPROVED** [review]

**Comment by djKooks** [comment]
Seems good~ @eskombro how do you think?

**Comment by eskombro** [comment]
Great, Thanks for the PR @widlok and @djKooks for the review!

As @widlok said in #42 there is a problem with the integration test:

```
com.meilisearch.integration.DocumentsTest > testDeleteDocuments() FAILED
    java.lang.IllegalStateException at DocumentsTest.java:218
```

Can you please check that?

Let me know when it is working or if you need any help :)

**Comment by widlok** [comment]
Thanks for reply @eskombro . I run those tests before posting but for some reason all tests fail with error

`Connection refused: connect
java.net.ConnectException: Connection refused: connect`

```
at com.meilisearch.sdk.http.DefaultHttpClient.execute(DefaultHttpClient.java:53)
	at com.meilisearch.sdk.http.DefaultHttpClient.post(DefaultHttpClient.java:73)
	at com.meilisearch.sdk.MeiliSearchHttpRequest.post(MeiliSearchHttpRequest.java:38)
	at com.meilisearch.sdk.IndexesHandler.create(IndexesHandler.java:46)
	at com.meilisearch.sdk.IndexesHandler.create(IndexesHandler.java:28)
	at com.meilisearch.sdk.Client.createIndex(Client.java:36)
	at com.meilisearch.integration.ClientTest.testDeleteIndex(ClientTest.java:109)
```

**Comment by eskombro** [comment]
> `Connection refused: connect java.net.ConnectException: Connection refused: connect`

Is your MeiliSearch instance running? Seems to be down

**Comment by widlok** [comment]
I develop on windows, i cant find option of Meilisearch for windows 10.

**Comment by eskombro** [comment]
@widlok you can [download the windows binary](https://github.com/meilisearch/MeiliSearch/releases/download/v0.15.0/meilisearch-windows-amd64.exe) from the [MeiliSearch Release page](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0)!

You can also use docker, or create a remote instance in [MeiliSearch Sandbox](https://sandbox.meilisearch.com/)!

**Comment by widlok** [comment]
Thanks for advice! Docker looks most convenient , new PR up for a review :)

**Review by eskombro — APPROVED** [review]
Thanks for the PR @widlok !

I see that you refactored a little bit the test classes, its ok 👍 

Is there any reason to prefer using a `List` of identifiers instead of an `Array`? This is out of curiosity, because as I have stated, I'm no java expert, and I'm interested in understanding those choices, since soon it will be important to check that there is a coherence between the methods and the data types we use on them!

Thank you very much! Tests work perfectly now 👌

**Comment by eskombro** [comment]
Can you please rebase your branch on master and ping me when it's all good?

**Comment by widlok** [comment]
> Is there any reason to prefer using a `List` of identifiers instead of an `Array`? This is out of curiosity, because as I have stated, I'm no java expert, and I'm interested in understanding those choices, since soon it will be important to check that there is a coherence between the methods and the data types we use on them, and choices will have to be consistent

Operating on Arrays can be a bit cumbersome in Java. Lists and Streams have fancy one liners to iterate through it, filter it, map it etc. which makes code immensely more readable and reduce number of code lines . You could use Arrays over List if iterating over it becomes performance bottleneck but nowadays most bottlenecks are  I/O operations more than CPU operations.
Cheers Chris.

**Review by eskombro — APPROVED** [review]
👌 LGTM, Thanks a lot!

**Comment by eskombro** [comment]
Thanks for your explanation @widlok! :)

A note: I just realized after merging that your commits are being registered as anonymous commits (and not listed in the contributors), maybe a missconfiguration on your git config!

**Comment by widlok** [comment]
Thanks for the info @eskombro ! My git tried to force me to become unnamed hero, Its fixed now :)

**Comment by eskombro** [comment]
@widlok Oh that nasty Git! :)

**Pull request merged**
