### PR TITLE
only sign release versions (enable use via jitpack)

### PR DESCRIPTION
**Pull request by tropikoder**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by brunoocasali** [comment]
Hi, @tropikoder thanks for your PR! 

Before going further, can you help me understand why this is good for this repo?

**Comment by brunoocasali** [comment]
@alallema this change is good for us, I tried to use jitpack to test your refactor branch but I couldn't because of the signing issue the contributor sent :)

**Comment by brunoocasali** [comment]
But I did not check if it really works :)

**Comment by alallema** [comment]
Yes! But I didn't think bors was going to delete the branch I thought I could edit the PR and change the base to main ...

**Pull request closed without merging**
