### PR TITLE
Add all-args-constructor for easy initial config Pagination

### PR DESCRIPTION
**Pull request by jonaskahn**
# Pull Request for Enhancement

## What does this PR do?
This is a tiny PR to make the Pagination initial more easier.
The current implementation make extra lines to config Pagination. Here is an example:

**Before**
```Kotlin
val index = meilisearchClient.index(it.getIndex())
val defaultPagination = Pagination()
defaultPagination.maxTotalHits = 5000
index.updatePaginationSettings(defaultPagination)
```
**After**
```Kotlin
val index = meilisearchClient.index(it.getIndex())
index.updatePaginationSettings(Pagination(5000))
```

### CODE REVIEW

**Comment by curquiza** [comment]
hello @jonaskahn 

Sorry for the delay 🙇‍♀️

Can you add a test for this new method?

**Comment by jonaskahn** [comment]
Ok. I'll add some test 👯

**Comment by jonaskahn** [comment]
@curquiza I added some tests. Could you please review it again? 
Thank you

**Review by curquiza — APPROVED** [review]
thank you @jonaskahn 

bors merge

**Pull request merged**
