### PR TITLE
Unify project name as `MeiliSearch` in comments

### PR DESCRIPTION
**Pull request by djKooks**
Hello.

I've found that usage of 'Meilisearch' and 'MeiliSearch' are mixed in this project. Seems official naming are 'MeiliSearch', so I updated the comments.

Please look on 🙏

### CODE REVIEW

**Review by bidoubiwa — APPROVED** [review]
Thanks a lot for this attention to detail 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Review by eskombro — APPROVED** [review]
LGTM, Thanks! 🎉

**Comment by bidoubiwa** [comment]
bors merge

**Comment by eskombro** [comment]
bors merge

**Pull request merged**
