### PR TITLE
Create new Details class and add Details field in Task class

### LINKED ISSUE #331: Adding `details` field to `Task` class
The Java class `Task` which retrieves the response from `Meilisearch` for a task contains these fields:
```
    protected String status = "";
    protected int uid = 0;
    protected String indexUid = "";
    protected String type = null;
    protected String duration = "";
    protected Date enqueuedAt = null;
    protected Date startedAt = null;
    protected Date finishedAt = null;
    protected TaskError error = null;
```
But the actual response send by `Meilisearch` is like:
```
{
	"uid": 225,
	"indexUid": "WaitForTaskTimoutInMs",
	"status": "succeeded",
	"type": "documentAddition",
	"details": {
		"receivedDocuments": 30,
		"indexedDocuments": 30
	},
	"duration": "PT0.031713875S",
	"enqueuedAt": "2022-01-26T16:54:46.993341418Z",
	"startedAt": "2022-01-26T16:54:46.995596001Z",
	"finishedAt": "2022-01-26T16:54:47.027309876Z"
},
```
It should be more accurate to add a `details` field to the `Task` class to be able to have the entire answer from the `Meilisearch` API.

### PR DESCRIPTION
**Pull request by kuruvasatya**
# Pull Request

## What does this PR do?
Fixes #331
Created new Details class and added the Details field to Task class

## PR checklist
Please check if your PR fulfills the following requirements:
- [ x ] Does this PR fix an existing issue?
- [ x ] Have you read the contributing guidelines?
- [ x ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to MeiliSearch!

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @kuruvasatya for this PR!
The code is great can you just add some tests to check if the `details` class works well?
In this file `src/test/java/com/meilisearch/integration/TasksTest.java` there are tests on the Task class you can just add for example in the `testClientGetTask`:
```
assertNotNull(task.getDetails());
assertNull(task.getDetails().getPrimaryKey());
```

**Comment by kuruvasatya** [comment]
Hey @alallema , can you tell what I am doing wrong

**Comment by alallema** [comment]
> Hey @alallema , can you tell what I am doing wrong

Hi @kuruvasatya,
Yes, you try to test the `primaryKey` in `details` fields for all tasks and some are `null` but some are equal to a value. That's why it's failed don't bother you, you can remove this lines 63-65:
```
            if (task.getType().equals("indexCreation")) {
                assertNull(task.getDetails().getPrimaryKey());
            }
```
You rest of your tests is enough! Good job 🔥

**Review by alallema — APPROVED** [review]
LGTM!
Thank for contributing to Meilisearch ❤️

**Comment by alallema** [comment]
bors merge

**Pull request merged**
