### PR TITLE
implement Keys API based on ServiceTemplate 

### PR DESCRIPTION
**Pull request by niemannd**
⚠️ This PR includes #120 and #121 

This AP contains the API for the /keys endpoint.

### CODE REVIEW

**Comment by eskombro** [comment]
Hey @niemannd !

Amazing, thanks! This PRs will be reviewed next week if that's ok for you, but this is great!

**Review by eskombro — APPROVED** [review]
Thanks for updating the branch @niemannd ! This PR seems ready to me. Let me know if it is the case for you too!

**Comment by eskombro** [comment]
bors try

**Comment by niemannd** [comment]
LGTM

**Comment by eskombro** [comment]
Bors merge

**Comment by eskombro** [comment]
Bors merge

**Pull request merged**
