### PR TITLE
Support user-dictionary loading #660

### LINKED ISSUE #660: [v1.4] Support user-dictionary loading
*Following this [central issue](https://github.com/meilisearch/integration-guides/issues/286)*

- [ ]  Add a new setting: `dictionary` with `get`, `update`, and `reset` methods associated.
Here are the JS equivalents in meilisearch-js you should create for this repository:

```jsx
client.index('indexName').getDictionary(); // calls GET /indexes/:uid/settings/dictionary
client.index('indexName').updateDictionary(['|', '/', '&sep']);  // calls PUT /indexes/:uid/settings/dictionary
client.index('indexName').resetDictionary(); // calls DELETE /indexes/:uid/settings/dictionary
```

- [ ]  The methods associated with the `/settings` API route (to get, reset and update the settings globally) must be able to receive in the payload the new configuration `dictionary`.
- [ ]  ⚠️ Add integration tests ⚠️
- [ ]  Update the `.code-samples.meilisearch.yaml`
    - [ ]  Add `get_dictionary_1` key and “translate” the following curl example by using the newly added methods: https://github.com/meilisearch/documentation/blob/2060089a5c10bcd0beb28633062f90cf0b279f7f/.code-samples.meilisearch.yaml#L1133
    - [ ]  Add `update_dictionary_1` key and “translate” the following curl example by using the newly added methods: https://github.com/meilisearch/documentation/blob/2060089a5c10bcd0beb28633062f90cf0b279f7f/.code-samples.meilisearch.yaml#L1136
    - [ ]  Add `reset_dictionary_1` key and “translate” the following curl example by using the newly added methods: https://github.com/meilisearch/documentation/blob/2060089a5c10bcd0beb28633062f90cf0b279f7f/.code-samples.meilisearch.yaml#L1144

### PR DESCRIPTION
**Pull request by mesutgk15**
# Pull Request

## Related issue
Fixes #660

## What does this PR do?
- Add a new setting as dictionary and get, update, reset methods for this setting 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by mesutgk15** [comment]
Hello @brunoocasali, had the chance to review?

**Review by brunoocasali — DISMISSED** [review]
bors merge

**Comment by brunoocasali** [comment]
Hey @mesutgk15 it seems we have an issue with the coverage. Can you check if this is really the case or is a bug in the coverage config?

**Comment by brunoocasali** [comment]
I'll wait your feedback before releasing the next version :)

**Review by brunoocasali — APPROVED** [review]
bors merge

**Pull request merged**
