### PR TITLE
Change of get method to post method in the sdk

### PR DESCRIPTION
**Pull request by mayralgr**
Change of method in Search Java
For the issue: Migrate search from GET to POST #54

### CODE REVIEW

**Comment by mayralgr** [comment]
@curquiza Sorry for the bother, do you know if any further changes must be done? I am a little confused as I think it is all.
Also, test must be done, right? Finally, do you know if it is necessary to completely delete the get definition?

**Comment by curquiza** [comment]
Hello @mayralgr! Thanks for your PR!

This is indeed a good start but I'm not sure this is done: as you can see the tests in the CI are failing! :wink: This indicates not only this change might be needed, or maybe the tests need to be updated. Maybe @eskombro can help you on this point!

Check out our CONTRIBUTING.md file to know how to run the tests locally: https://github.com/meilisearch/meilisearch-java/blob/master/CONTRIBUTING.md#development-workflow

Once you've finished with your PR, don't forget to remove the `draft` status of this PR, so that we know we can review it!

**Comment by eskombro** [comment]
Hi @mayralgr 

This change actually needs to modify the way the parameters are sent to MeiliSearch. When performing a search request, the parameters are encoded in the URL and sent to the MeiliSearch server as key/value pairs in the URL itself in the form of:

```
http://<url>/indexes/<index-uid>/search?key=value&key=value&key=value
```

But to perform a POST search request, all of this parameters have to be sent as a JSON in the body of the request.

If you run the tests on your branch you will see a few errors like this:

Screenshot 2020-12-03 at 15 50 00

(you can run them with: `./gradlew test IntegrationTest --info`)

This means that the JSON body you are sending is empty and MeiliSearch doesn't know the details of the search request you are trying to perform

**Comment by mayralgr** [comment]
@curquiza @eskombro thank you both. I am working in the JSON, I already modify some tests and code and as soon as I have the pr ready I let you know. Thanks a lot for the help 😄

**Comment by mayralgr** [comment]
@eskombro @curquiza all up, let me know if I am missing something 😄

**Review by eskombro — APPROVED** [review]
Thanks a lot for this contribution @mayralgr!

It seems to be working perfectly and there is nothing missing!

🎉

**Comment by eskombro** [comment]
Bors try

**Comment by eskombro** [comment]
Bors merge

**Pull request merged**
